export const TAXONOMY = {
  domains: [
    "llm",
    "diffusion",
    "systems",
    "security",
    "research",
    "other",
  ] as const,
  domainLabels: {
    all: "All Domains",
    llm: "LLMs & Transformers",
    diffusion: "Diffusion Models",
    systems: "Systems & Infra",
    security: "Cybersecurity & IAM",
    research: "Research & Benchmarks",
  },
  domainTags: [
    "LLM",
    "Diffusion Models",
    "Transformers",
    "RLHF",
    "Cybersecurity",
    "Systems",
    "Infra",
    "Research",
  ] as const,
  techniqueTags: [
    "RoPE",
    "RMSNorm",
    "SwiGLU",
    "KV-Cache",
    "Mixed Precision",
    "Attention",
    "Fine-Tuning",
    "Quantization",
    "CLIP",
    "U-Net",
    "DDPM",
    "DDIM",
    "CFG",
    "SailPoint",
    "IAM",
    "DoS Mitigation",
  ] as const,
  toolingTags: [
    "PyTorch",
    "CUDA",
    "Python",
    "Docker",
    "C++",
    "Linux",
  ] as const,
};
