export const TAXONOMY = {
  domains: [
    "llm",
    "diffusion",
    "systems",
    "rec-sys",
    "security",
    "research",
    "other",
  ] as const,
  domainLabels: {
    all: "All Domains",
    llm: "LLMs & Transformers",
    diffusion: "Diffusion Models",
    systems: "Systems & Infrastructure",
    "rec-sys": "Sequential Recommendation",
    security: "Cybersecurity & IAM",
    research: "Research & Benchmarks",
  },
  domainTags: [
    "LLM",
    "Diffusion Models",
    "Transformers",
    "RLHF",
    "Cybersecurity",
    "Systems",
    "Infra",
    "Recommendation",
    "Sequential RecSys",
    "Research",
  ] as const,
  techniqueTags: [
    "RoPE",
    "RMSNorm",
    "SwiGLU",
    "KV-Cache",
    "Mixed Precision",
    "Attention",
    "Fine-Tuning",
    "Quantization",
    "CLIP",
    "U-Net",
    "DDPM",
    "DDIM",
    "CFG",
    "LoRA Hot-Swapping",
    "Dense Retrieval",
    "Sparse Retrieval",
    "RRF",
    "Cross-Encoder",
    "NLI",
    "Sequential Modeling",
    "Self-Attention RecSys",
    "BPE Fragmentation",
    "Code-Mixing",
    "SailPoint",
    "IAM",
    "DoS Mitigation",
  ] as const,
  toolingTags: [
    "PyTorch",
    "CUDA",
    "Python",
    "FAISS",
    "BM25",
    "Diffusers",
    "Docker",
    "C++",
    "Linux",
  ] as const,
};
